import { Link } from "wouter";
import { ArrowLeft, BarChart3, Bot, GitBranch, ShieldCheck, WalletCards } from "lucide-react";

const SECTIONS = [
  { icon: BarChart3, title: "About TradeCoin Exchange", text: "TradeCoin Exchange is a virtual e-commerce trading marketplace. Users receive simulated TC and virtual product holdings, then practice making decisions in a live-style market without real-money payments." },
  { icon: WalletCards, title: "How to trade", text: "Choose a product, review its price history and order book, then place a Buy or Sell limit order. Buy orders reserve TC; sell orders reserve units. When compatible orders meet, the backend settles the exchange and records the completed trade." },
  { icon: GitBranch, title: "The matching algorithm", text: "The exchange uses server-side price-time priority. For buys, the highest price has priority; for sells, the lowest price has priority. When prices are compatible, the earlier order at that price is matched first. Partial fills are supported, and settlement is atomic so balances and holdings cannot be left half-updated." },
  { icon: BarChart3, title: "How to trade more effectively", text: "There is no guaranteed profitable strategy. Use the chart and public order book to compare price, spread, volume, and available liquidity. Consider smaller orders, avoid chasing sudden moves, and keep track of the difference between your entry price and the current reference price. Profit and loss indicators are educational estimates, not promises." },
  { icon: Bot, title: "TradeCoin Market Maker", text: "The TradeCoin Market Maker is a virtual liquidity provider operated by the exchange. It seeds built-in products with inventory and sell orders so new users can buy units from the beginning. The market maker may therefore appear as the seller in the order book. It is part of the simulation and does not represent a real person or financial institution." },
  { icon: ShieldCheck, title: "Virtual economy and transparency", text: "All balances, products, orders, trades, and prices are simulated. The backend is the source of truth, orders are visible in the public market book, and completed trades appear in the online activity feed. Nothing on this website is a real-money investment or financial advice." },
];

export default function About() {
  return <div className="site-shell min-h-screen bg-[#071019] text-slate-100"><header className="border-b border-white/[0.07] bg-[#071019]/90 px-4 py-5 backdrop-blur-xl"><div className="mx-auto flex max-w-5xl items-center justify-between"><Link href="/" className="flex items-center gap-2 text-sm font-bold text-slate-100"><ArrowLeft size={16} className="text-[#69ddbd]" /> Back to exchange</Link><div className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-500">TradeCoin guide</div></div></header><main className="mx-auto max-w-5xl px-4 py-12 sm:px-6"><div className="max-w-3xl"><div className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#69ddbd]">Learn the market</div><h1 className="mt-3 text-3xl font-bold tracking-tight text-white sm:text-5xl">About TradeCoin Exchange</h1><p className="mt-4 text-sm leading-7 text-slate-400">Understand how the virtual marketplace works, how orders are matched, and why the TradeCoin Market Maker sometimes appears as the seller.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2">{SECTIONS.map(({ icon: Icon, title, text }) => <section key={title} className="rounded-2xl border border-white/[0.08] bg-[#0b1722]/85 p-5"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#69ddbd]/10 text-[#69ddbd]"><Icon size={19} /></div><h2 className="mt-5 text-base font-bold text-slate-100">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-400">{text}</p></section>)}</div></main></div>;
}
