import { trpc } from "@/lib/trpc";
import { BarChart3, Package, PencilLine, Plus } from "lucide-react";
import { Link } from "wouter";
import { AdminFrame, AdminGate } from "./AdminShared";

function Dashboard() {
  const products = trpc.admin.products.useQuery();
  return <AdminFrame title="Administrator overview" description="Manage the virtual product catalog and simulated market prices."><div className="grid gap-4 md:grid-cols-3"><Link href="/administrator/add" className="group rounded-2xl border border-[#69ddbd]/25 bg-[#69ddbd]/[0.06] p-5 transition hover:-translate-y-0.5"><Plus className="text-[#69ddbd]" size={20} /><h2 className="mt-5 font-bold">Add product</h2><p className="mt-1 text-xs text-slate-500">Create a new product market.</p></Link><Link href="/administrator/edit" className="group rounded-2xl border border-white/[0.08] bg-[#0b1823] p-5 transition hover:-translate-y-0.5"><PencilLine className="text-violet-300" size={20} /><h2 className="mt-5 font-bold">Edit product</h2><p className="mt-1 text-xs text-slate-500">Rename, describe, reprice, or drop products.</p></Link><div className="rounded-2xl border border-white/[0.08] bg-[#0b1823] p-5"><BarChart3 className="text-amber-200" size={20} /><h2 className="mt-5 font-bold">Catalog size</h2><p className="mt-1 text-3xl font-bold text-[#69ddbd]">{products.data?.length ?? "—"}</p><p className="text-xs text-slate-500">active product markets</p></div></div><section className="mt-6 rounded-2xl border border-white/[0.08] bg-[#0b1823] p-5"><div className="mb-4 flex items-center gap-2"><Package size={17} className="text-[#69ddbd]" /><h2 className="text-sm font-bold">Current catalog</h2></div>{products.isLoading ? <p className="py-8 text-center text-sm text-slate-500">Loading products…</p> : <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{products.data?.map((product) => <div key={product.id} className="rounded-xl border border-white/[0.07] bg-white/[0.02] p-3"><div className="truncate text-sm font-semibold">{product.name}</div><div className="mt-1 text-[10px] uppercase tracking-wider text-slate-500">{product.category} · {Number(product.currentPrice).toFixed(2)} TC</div></div>)}</div>}</section></AdminFrame>;
}

export default function Administrator() { return <AdminGate><Dashboard /></AdminGate>; }
