import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { PackagePlus } from "lucide-react";
import { AdminFrame, AdminGate, PinConfirm } from "./AdminShared";

function AddForm() {
  const [name, setName] = useState(""); const [category, setCategory] = useState("Technology"); const [description, setDescription] = useState(""); const [price, setPrice] = useState(""); const [confirmOpen, setConfirmOpen] = useState(false);
  const create = trpc.admin.createProduct.useMutation(); const utils = trpc.useUtils();
  async function submit(pin: string) { try { await create.mutateAsync({ name, category, description, price, pin }); setName(""); setDescription(""); setPrice(""); setConfirmOpen(false); await Promise.all([utils.admin.products.invalidate(), utils.markets.products.invalidate()]); toast.success("Product added to the marketplace"); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not add product"); } }
  function discard() { setName(""); setCategory("Technology"); setDescription(""); setPrice(""); setConfirmOpen(false); }
  return <AdminFrame title="Add product" description="Create a new virtual market. Description is optional."><section className="max-w-3xl rounded-2xl border border-white/[0.08] bg-[#0b1823] p-5"><div className="mb-5 flex items-center gap-2"><PackagePlus size={18} className="text-[#69ddbd]" /><h2 className="text-sm font-bold">Product details</h2></div><div className="grid gap-4 sm:grid-cols-2"><div><label className="text-xs font-semibold text-slate-300">Product name</label><input value={name} onChange={(event) => setName(event.target.value)} className="field-input mt-2" required placeholder="e.g. Aurora Devices" /></div><div><label className="text-xs font-semibold text-slate-300">Category</label><input value={category} onChange={(event) => setCategory(event.target.value)} className="field-input mt-2" required placeholder="Technology" /></div><div><label className="text-xs font-semibold text-slate-300">Starting price (TC)</label><input value={price} onChange={(event) => setPrice(event.target.value)} className="field-input mt-2" inputMode="decimal" required placeholder="100.00" /></div><div className="sm:col-span-2"><label className="text-xs font-semibold text-slate-300">Description <span className="font-normal text-slate-500">(optional)</span></label><textarea value={description} onChange={(event) => setDescription(event.target.value)} className="field-input mt-2 h-28 py-3" placeholder="What does this product represent?" /></div></div><button disabled={!name.trim() || !price || !category.trim()} onClick={() => setConfirmOpen(true)} className="mt-5 rounded-xl bg-[#69ddbd] px-5 py-3 text-xs font-bold text-[#062a2b] disabled:opacity-50">Confirm changes</button></section><PinConfirm open={confirmOpen} title="Enter your PIN to add this product." onConfirm={(pin) => void submit(pin)} onCancel={discard} pending={create.isPending} /></AdminFrame>;
}
export default function AdminAddProduct() { return <AdminGate><AddForm /></AdminGate>; }
